/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aniruddha' at '3/4/17 2:07 PM' with Gradle 2.14.1
 *
 * @author aniruddha, @date 3/4/17 2:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
